# Generated by Django 4.0.6 on 2023-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('rol', models.CharField(choices=[('bodeguero', 'bodeguero'), ('administrador', 'administrador')], max_length=45)),
                ('correo', models.EmailField(max_length=45)),
            ],
        ),
    ]
