# Generated by Django 4.0.6 on 2023-05-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_generico_1', models.AutoField(primary_key=True, serialize=False)),
                ('id_compra', models.CharField(max_length=45)),
                ('proveedor', models.CharField(max_length=45)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('total_compra', models.PositiveIntegerField(default=0)),
                ('Empleado_id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_de_barras', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_generico_3', models.AutoField(primary_key=True, serialize=False)),
                ('id_venta', models.CharField(max_length=45)),
                ('cliente', models.CharField(max_length=45)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('total_venta', models.PositiveIntegerField(default=0)),
                ('Empleado_id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.empleado')),
                ('Producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id_generico_2', models.AutoField(primary_key=True, serialize=False)),
                ('id_recepcion', models.CharField(max_length=45)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado_recepcion', models.CharField(choices=[('por recibir', 'por recibir'), ('recibido', 'recibido'), ('pendiente por revision', 'pendiente por revision')], max_length=45)),
                ('notas_recepcion', models.CharField(max_length=45)),
                ('Compras_id_generico_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.compras')),
                ('Empleado_id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.empleado')),
                ('Producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_generico_5', models.AutoField(primary_key=True, serialize=False)),
                ('id_bodega', models.CharField(max_length=45)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('Producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.producto')),
                ('Recepcion_id_generico_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.recepcion')),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_generico_4', models.AutoField(primary_key=True, serialize=False)),
                ('id_entrega', models.CharField(max_length=45)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
                ('fecha_egreso', models.DateTimeField(auto_now_add=True)),
                ('estado_entrega', models.CharField(choices=[('por entregar', 'por entregar'), ('entregado', 'entregado'), ('pendiente por revision', 'pendiente por revision')], max_length=45)),
                ('notas_entrega', models.CharField(max_length=45)),
                ('Empleado_id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.empleado')),
                ('Producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.producto')),
                ('Ventas_id_generico_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.ventas')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='Producto_id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.producto'),
        ),
    ]
