# Generated by Django 4.0.6 on 2023-05-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0002_compras_producto_ventas_recepcion_inventario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregas',
            old_name='fecha_egreso',
            new_name='fecha_despacho',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Recepcion_id_generico_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MGYP.recepcion'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_bodega',
            field=models.PositiveIntegerField(max_length=45),
        ),
    ]
