# Generated by Django 4.0.6 on 2023-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0003_rename_fecha_egreso_entregas_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_bodega',
            field=models.PositiveIntegerField(),
        ),
    ]
