# Generated by Django 4.0.6 on 2023-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0004_alter_inventario_id_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.PositiveIntegerField(),
        ),
    ]
