# Generated by Django 4.0.6 on 2023-05-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0008_alter_producto_peso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='Empleado_id_empleado',
            new_name='Empleado_id_empleado_id',
        ),
    ]
