# Generated by Django 4.0.6 on 2023-05-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0009_rename_empleado_id_empleado_historial_empleado_id_empleado_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='id_generico_6',
        ),
        migrations.AddField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
