# Generated by Django 4.0.6 on 2023-05-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0010_remove_historial_id_generico_6_historial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
    ]
