# Generated by Django 4.0.6 on 2023-05-24 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0012_actividad_delete_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregas',
            old_name='Empleado_id_empleado',
            new_name='id_empleado',
        ),
        migrations.RenameField(
            model_name='entregas',
            old_name='Ventas_id_generico_3',
            new_name='id_venta',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_generico_5',
            new_name='id_inventario',
        ),
        migrations.RenameField(
            model_name='recepcion',
            old_name='Compras_id_generico_1',
            new_name='id_compra',
        ),
        migrations.RenameField(
            model_name='recepcion',
            old_name='Empleado_id_empleado',
            new_name='id_empleado',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='Empleado_id_empleado',
            new_name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='Producto_id_producto',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='id_generico_1',
        ),
        migrations.RemoveField(
            model_name='entregas',
            name='Producto_id_producto',
        ),
        migrations.RemoveField(
            model_name='entregas',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='entregas',
            name='id_generico_4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='Producto_id_producto',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='id_generico_2',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='Producto_id_producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_generico_3',
        ),
        migrations.AddField(
            model_name='compras',
            name='lista_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregas',
            name='cantidades_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregas',
            name='lista_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='cantidades_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='id_bodega',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='lista_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='cantidades_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='lista_productos',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compras',
            name='id_compra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='id_entrega',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barras',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='id_recepcion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
