# Generated by Django 4.0.6 on 2023-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0013_rename_empleado_id_empleado_entregas_id_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cantidad_producto',
            field=models.CharField(max_length=5000),
        ),
    ]
