# Generated by Django 4.0.6 on 2023-05-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0014_alter_compras_cantidad_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='Recepcion_id_generico_2',
            new_name='id_recepcion',
        ),
    ]
