# Generated by Django 4.0.6 on 2023-05-24 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0015_rename_recepcion_id_generico_2_inventario_id_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
