# Generated by Django 4.0.6 on 2023-05-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0017_remove_recepcion_notas_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='notas_recepcion',
            field=models.CharField(default='Notas', max_length=45),
            preserve_default=False,
        ),
    ]
