# Generated by Django 4.0.6 on 2023-05-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0018_recepcion_notas_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado_compra',
            field=models.CharField(choices=[('por recibir', 'por recibir'), ('recibido', 'recibido')], default='por recibir', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='estado_recepcion',
            field=models.CharField(choices=[('OK', 'OK'), ('pendiente por revision', 'pendiente por revision')], max_length=45),
        ),
    ]
