# Generated by Django 4.0.6 on 2023-05-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0019_compras_estado_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado_compra',
            field=models.CharField(choices=[('por recibir', 'por recibir'), ('recibida', 'recibida')], max_length=45),
        ),
    ]
