# Generated by Django 4.0.6 on 2023-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0020_alter_compras_estado_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.PositiveIntegerField(default=2000)),
                ('esta_lleno', models.BooleanField(default=False)),
            ],
        ),
    ]
