# Generated by Django 4.0.6 on 2023-05-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0023_alter_recepcion_id_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGYP.bodega'),
        ),
    ]
