# Generated by Django 4.0.6 on 2023-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0024_alter_inventario_id_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Producto_id_producto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad_producto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidades_productos',
            field=models.CharField(default='0', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='lista_productos',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
