# Generated by Django 4.0.6 on 2023-05-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0025_remove_inventario_producto_id_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidades_productos',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id_recepcion',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='lista_productos',
            field=models.CharField(max_length=10000),
        ),
    ]
