# Generated by Django 4.0.6 on 2023-05-25 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0026_remove_inventario_cantidades_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estado_venta',
            field=models.CharField(choices=[('por entregar', 'por entregar'), ('entregada', 'entregada')], default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
