# Generated by Django 4.0.6 on 2023-05-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0027_ventas_estado_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cantidades_productos',
        ),
    ]
