# Generated by Django 4.0.6 on 2023-05-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0028_remove_ventas_cantidades_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='cantidades_productos',
        ),
    ]
