# Generated by Django 4.0.6 on 2023-05-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0030_ventas_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='estado_entrega',
            field=models.CharField(choices=[('OK', 'OK'), ('pendiente por revision', 'pendiente por revision')], max_length=45),
        ),
    ]
