# Generated by Django 4.0.6 on 2023-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0031_alter_entregas_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='cantidades_productos',
            field=models.CharField(default='2 1', max_length=5000),
            preserve_default=False,
        ),
    ]
