# Generated by Django 4.0.6 on 2023-05-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0036_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barras',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
