# Generated by Django 4.0.6 on 2023-05-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGYP', '0037_alter_producto_codigo_de_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
